#! /usr/bin/env php

<?php

use Acme\SayHelloCommand;
use Acme\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Laracasts Demo', '1.0');

$app->add(new SayHelloCommand);
$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();
