#! /usr/bin/env php

<?php

use Acme\AddCommand;
use Acme\ShowCommand;
use Acme\CompleteCommand;
use Acme\DatabaseAdapter;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Tasks App', '1.0');

try {
    $pdo = new PDO('sqlite:db.sqlite');

    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Exception $exception) {
    echo 'Could not connect to the database';
    exit(1);
}

$dbAdapter = new DatabaseAdapter($pdo);

$app->add(new ShowCommand($dbAdapter));
$app->add(new AddCommand($dbAdapter));
$app->add(new CompleteCommand($dbAdapter));

$app->run();
